=== kayh/ghp/v1.1.5/model/json-schema-v3/submit-mailpiece.json
{
  "$schema": "http://json-schema.org/draft-03/schema#",
  "definitions": {},
  "type": "object",
  "properties": {
    "mailpieceId": {
      "type": "string",
      "description": "Represents the national identifier for the mailpiece item.",
      "pattern": "(98|99)[0-9]{16}",
      "required": true
    },
    "timestamp": {
      "type": "string",
      "description": "[extension]\r\n\r\nTimestamp of data collection.",
      "format": "date-time",
      "required": true
    },
    "sourceId": {
      "type": "string",
      "description": "Refers to a module id as event-source.  ",
      "pattern": "[A-Z]{3}[0-9]{2}",
      "required": true
    },
    "mpAttr": {
      "$ref": "mailpiece-attr.json",
      "description": "The MailpieceAttrT type is assigned to the element mp_attr. It provides basic\r\nmailpiece related information:\r\n\r\n- the kind of the mail item\r\n- the mailclass of the mail item; important for the ED because it and may affect the address recognition\r\n- the scanned faces of the mail item. The FaceSetT type is assigned to faces and allows providing a sequence of faces. \r\n   The FaceSetT types allows to link a face with the corresponding image by a page attribute.\r\n- a preknowledge result if a barcode reader or some other type of Enrichment Device is directly attached to the MC.\r\n   This result will be in accordance with the result type specified in the IC-ED interface."
    }
  },
  "additionalProperties": false,
  "id": "SubmitMailpiece"
}

=== kayh/ghp/v1.1.5/samples/generated-SubmitMailpiece.json
{
   "sourceId": "DWS01",
   "mailpieceId": "993413796700000321",
   "mpAttr": {
      "preknowledge": {
         "binOccupancy": {
            "frontOverlappingLimitExceeded": false,
            "multipleItemsDetected": false,
            "emptyBinOccupied": false,
            "conveyingAidDetected": false,
            "backOverlappingLimitExceeded": false,
            "binMultipleItemOccupied": false
         },
         "legalForTrade": {
            "shape": "IRREGULAR",
            "boxVolume": 9280,
            "actualVolume": 3659,
            "state": {
               "dimensionError": false,
               "storageError": false,
               "conveyorSpeedError": false,
               "weightError": false
            },
            "volumeRatio": 0
         },
         "multipleMailpiecdIdRecognized": false,
         "weight": {
            "state": {
               "scaleDataFormatError": false,
               "conveyorSpeedChangedDuringMeasurement": false,
               "invalidMeasurement": false,
               "conveyorSpeedOutOfMaxLimit": false,
               "externalError": false,
               "packageLengthError": false,
               "underweight": true,
               "overload": false,
               "underload": false,
               "alibiStorageAtScaleFailed": false,
               "packageDistanceError": false,
               "isLegalForTrade": false,
               "overweight": false
            },
            "value": 860
         },
         "location": {
            "face": "TOP",
            "polygon": {
               "dot": [{
                  "x": -11,
                  "y": 117
               }, {
                  "x": 2,
                  "y": 455
               }, {
                  "x": 419,
                  "y": 101
               }, {
                  "x": 432,
                  "y": 439
               }]
            }
         },
         "dimension": {
            "length": 429,
            "width": 338,
            "state": {
               "measurementResult": "OK",
               "itemSizeClassification": {
                  "oversized": false,
                  "undersized": false,
                  "ok": true
               },
               "measurementRange": "INSIDE"
            },
            "height": 64
         },
         "barCodes": [{
            "type": "CODE_128",
            "value": "010780",
            "status": "DETECTED_AND_RECOGNIZED"
         }, {
            "type": "CODE_128",
            "value": "993413796700000321",
            "status": "DETECTED_AND_RECOGNIZED"
         }]
      },
      "type": "PARCEL"
   },
   "timestamp": "2019-09-02T14:12:32.7240451+02:00"
}
